export const dummyData = [
    {
        "id":1,
        "firstName":"ajith",
        "lastname":"theerthiya",
        "email":"ajiee@gmail.com"
    },
    {
        "id":2,
        "firstName":"arun",
        "lastname":"katacharayan",
        "email":"arun@gmail.com"
    },
    {
        "id":3,
        "firstName":"bavi",
        "lastname":"iswariya",
        "email":"bavi@gmail.com"
    },
    {
        "id":4,
        "firstName":"anish",
        "lastname":"raj",
        "email":"raj@gmail.com"
    }
]